"""Initial setup with Channels and Subscriptions

Revision ID: 326354428411
Revises: 
Create Date: 2025-04-30 17:07:28.924014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326354428411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin_role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_channel_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel')),
    sa.UniqueConstraint('user_id', name=op.f('uq_channel_user_id'))
    )
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_name'), ['name'], unique=True)

    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name='fk_subscriptions_channel_id_channel'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], name='fk_subscriptions_subscriber_id_user'),
    sa.PrimaryKeyConstraint('subscriber_id', 'channel_id', name=op.f('pk_subscriptions'))
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_filename', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_video_channel_id_channel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video'))
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_filename'), ['filename'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_comment_video_id_video')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_filename'))
        batch_op.drop_index(batch_op.f('ix_video_channel_id'))

    op.drop_table('video')
    op.drop_table('subscriptions')
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_name'))

    op.drop_table('channel')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
